### PR TITLE
l500d: fix camera clicking/ticking noise when the device is idle.

### PR DESCRIPTION
**Pull request by krnlyng**
msm_actuator_park_lens was never called.
call it when the subdev is closed. this reduces the amount of clicks to one single click when:
* the camera app is closed
* a different camera is selected inside camera app
* the flashlight is turned off

but there are no random clicks when the device is just idling.

### CODE REVIEW

**Comment by KonstaT** [comment]
Thanks, but I wasn't planning on merging any third party fixes here (not to this branch at least). This is just unmodified source release from Jolla. Apparently there's also source releases for 2.0.4.14 and 2.0.5.6 builds (http://releases.sailfishos.org/sources/). I'll add merging those to my todo list.

I'll leave this open in case anyone wants to pick it up.

**Comment by krnlyng** [comment]
@KonstaT thanks for leaving it open :), i was advised by @sledges to post the fix here to have it easily accessible.

btw.: i have just tried 1 instead of max_code_size as value for max_step but that causes a hard crash and the camera lens goes wild, this doesn't happen with max_code_size so i hope it is safe (been using it at work and at home with no issue whatsoever).

**Comment by krnlyng** [comment]
this will be fixed in the next sfos update so i think we can close this now.

**Comment by martonmiklos** [comment]
@krnlyng Thank you so much for this fix!

**Comment by PaskoMoto** [comment]
Hi.
Just wanted to say thank you for this fix.

Regards.

**Pull request closed without merging**
